package fusion:compositor;

interface types {
    record window-id {
        inner: u64,
    }
}

interface wm-imports {
    use types.{window-id};

    get-elements: func() -> list<window-id>;
    set-window-size: func(window: window-id, width: s32, height: s32);
    set-window-pos: func(window: window-id, x: s32, y: s32);

    get-output-size: func() -> tuple<s32, s32>;
}

interface wm-exports {
    use types.{window-id};

    new-toplevel: func(window: window-id);
    on-commit: func(window: window-id);
    toplevel-destroyed: func(window: window-id);
    rearrange-windows: func();
}
